### ISSUE TITLE
Proxy with authentication

### ISSUE THREAD

**Issue by yacosta738** [unprofession-al/proxyproxy#1]
It is possible to use a proxy that requires user and password authentication.
Example proxy: **192.168.44.244**
               port: **3128**
               user: **username**
               password: **securepassword**

```
# Write a ton of logs?
verbose: true

# On which host:port should proxyproxy listen to. This is where you need to point your 
# applications to.
proxy_address: 127.0.0.1:8080

# Where should the management interface listen to. 
admin_address: 127.0.0.1:8081

# Which interface names should be watched for changes. This is matched via 'contains'.
# For example 'enp0' would match 'enp0s25'.
interfaces:
  - eth0
  - enp0
  - wlan0
  - wlo1

# The 'proxyproxy' configs:
proxy_proxy_configs:
  # Profile name
  company_a:
    # Do a man in the middle... Currently this must be 'false'
    # Also if you want to set this to 'true' at one point, make sure you have read
    # the code! MITM can be evil...
    mitm: false
    # The 'company_a' profile will be used if an IP af the interfaces in in the
    # following subnet:
    in_net: 192.168.44.0/24
    # 'proxyproxy' will then redirect your traffic to the following proxy server 
    remote_proxy: "http://username:securepassword@192.168.44.244:3128"

# If no profile is matched, no proxy server is used. 'proxyproxy' sends your 
# requests to the internet directly.
```
